version: '3.9'

services:
  gql-postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432 ## local 5433 / real database port 5432(fix)
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=jami
      - POSTGRES_USER=jami
      - POSTGRES_DB=postgres
