version: '3.9'

services:
  gql-postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5433
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=jami
      - POSTGRES_USER=jami
      - POSTGRES_DB=postgres
